# Generated by Django 4.2.1 on 2023-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eseme_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cour_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cour_description', models.TextField(blank=True, null=True)),
                ('cour_material', models.TextField(blank=True, null=True)),
                ('alterno', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('leve_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('leve_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('memb_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('memb_dni', models.TextField()),
                ('memb_typedni', models.CharField(blank=True, max_length=3, null=True)),
                ('memb_name', models.TextField()),
                ('memb_surname', models.TextField()),
                ('memb_mobil', models.TextField()),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('mode_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('mode_description', models.TextField(blank=True, null=True)),
                ('mode_status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('peri_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('peri_description', models.TextField(blank=True, null=True)),
                ('peri_start', models.DateField(blank=True, null=True)),
                ('peri_end', models.DateField(blank=True, null=True)),
                ('peri_status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('seas_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('seas_status', models.BooleanField(blank=True, null=True)),
                ('seas_glosa', models.TextField()),
            ],
            options={
                'db_table': 'season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stud_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('seas_final', models.SmallIntegerField(blank=True, null=True)),
                ('seas_ses01', models.BooleanField(blank=True, null=True)),
                ('seas_ses02', models.BooleanField(blank=True, null=True)),
                ('seas_ses03', models.BooleanField(blank=True, null=True)),
                ('seas_ses04', models.BooleanField(blank=True, null=True)),
                ('seas_ses05', models.BooleanField(blank=True, null=True)),
                ('seas_ses06', models.BooleanField(blank=True, null=True)),
                ('seas_ses07', models.BooleanField(blank=True, null=True)),
                ('seas_ses08', models.BooleanField(blank=True, null=True)),
                ('seas_ses09', models.BooleanField(blank=True, null=True)),
                ('seas_ses10', models.BooleanField(blank=True, null=True)),
                ('seas_ses11', models.BooleanField(blank=True, null=True)),
                ('seas_ses12', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='zones',
            options={'managed': False},
        ),
    ]
