# Generated by Django 4.2.1 on 2023-06-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eseme_app', '0002_course_levels_members_modes_periods_season_students_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='zones',
            table='zones',
        ),
    ]
