# Generated by Django 4.2.1 on 2023-12-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eseme_app', '0003_alter_schedule_table_alter_zones_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='periods',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zones',
            options={},
        ),
    ]
