# Generated by Django 4.2.1 on 2023-12-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eseme_app', '0004_alter_course_options_alter_levels_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='endime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='startime',
        ),
        migrations.RemoveField(
            model_name='zones',
            name='description',
        ),
        migrations.RemoveField(
            model_name='zones',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='cour_level',
            field=models.ForeignKey(blank=True, db_column='cour_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.levels'),
        ),
        migrations.AddField(
            model_name='members',
            name='memb_zone',
            field=models.ForeignKey(blank=True, db_column='memb_zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.zones'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sche_day',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sche_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sche_endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sche_id',
            field=models.SmallAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='sche_starttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='seas_course',
            field=models.ForeignKey(blank=True, db_column='seas_course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.course'),
        ),
        migrations.AddField(
            model_name='season',
            name='seas_mode',
            field=models.ForeignKey(blank=True, db_column='seas_mode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.modes'),
        ),
        migrations.AddField(
            model_name='season',
            name='seas_period',
            field=models.ForeignKey(blank=True, db_column='seas_period', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.periods'),
        ),
        migrations.AddField(
            model_name='season',
            name='seas_schedule',
            field=models.ForeignKey(blank=True, db_column='seas_schedule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.schedule'),
        ),
        migrations.AddField(
            model_name='season',
            name='seas_teacher',
            field=models.ForeignKey(blank=True, db_column='seas_teacher', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.members'),
        ),
        migrations.AddField(
            model_name='students',
            name='stud_member',
            field=models.ForeignKey(blank=True, db_column='stud_member', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.members'),
        ),
        migrations.AddField(
            model_name='students',
            name='stud_season',
            field=models.ForeignKey(blank=True, db_column='stud_season', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eseme_app.season'),
        ),
        migrations.AddField(
            model_name='zones',
            name='zone_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zones',
            name='zone_id',
            field=models.SmallAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='levels',
            table=None,
        ),
        migrations.AlterModelTable(
            name='members',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='periods',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schedule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='season',
            table=None,
        ),
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
        migrations.AlterModelTable(
            name='zones',
            table=None,
        ),
    ]
